services:
  db:
    image: postgres:14
    env_file: .env
    expose:
      - '5432'
    volumes:
      - GoPal:/var/lib/postgresql/data
      - ./init_data:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - gopal_net
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - NODE_ENV=development
      - DB_HOST=db
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - gopal_net
# This defines our volume(s), which will persist throughout startups.
# If you want to get rid of a hanging volume, e.g. to test your database init,
# run `docker-compose rm -v`. Note that this will remove ALL of your data, so
# be extra sure you've made a stable backup somewhere.
volumes:
  GoPal:
networks:
  gopal_net:
